// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PhotosColumns holds the columns for the "photos" table.
	PhotosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "original_name", Type: field.TypeString},
		{Name: "mime_type", Type: field.TypeString},
		{Name: "uploaded_at", Type: field.TypeTime},
		{Name: "user_photos", Type: field.TypeUUID},
	}
	// PhotosTable holds the schema information for the "photos" table.
	PhotosTable = &schema.Table{
		Name:       "photos",
		Columns:    PhotosColumns,
		PrimaryKey: []*schema.Column{PhotosColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "photos_users_photos",
				Columns:    []*schema.Column{PhotosColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_sessions", Type: field.TypeUUID},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PhotosTable,
		SessionsTable,
		UsersTable,
	}
)

func init() {
	PhotosTable.ForeignKeys[0].RefTable = UsersTable
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
}
