// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/parrotmac/pictorial/ent/photo"
	"github.com/parrotmac/pictorial/ent/predicate"
	"github.com/parrotmac/pictorial/ent/user"
)

// PhotoUpdate is the builder for updating Photo entities.
type PhotoUpdate struct {
	config
	hooks    []Hook
	mutation *PhotoMutation
}

// Where appends a list predicates to the PhotoUpdate builder.
func (pu *PhotoUpdate) Where(ps ...predicate.Photo) *PhotoUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetOriginalName sets the "original_name" field.
func (pu *PhotoUpdate) SetOriginalName(s string) *PhotoUpdate {
	pu.mutation.SetOriginalName(s)
	return pu
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (pu *PhotoUpdate) SetNillableOriginalName(s *string) *PhotoUpdate {
	if s != nil {
		pu.SetOriginalName(*s)
	}
	return pu
}

// SetMimeType sets the "mime_type" field.
func (pu *PhotoUpdate) SetMimeType(s string) *PhotoUpdate {
	pu.mutation.SetMimeType(s)
	return pu
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (pu *PhotoUpdate) SetNillableMimeType(s *string) *PhotoUpdate {
	if s != nil {
		pu.SetMimeType(*s)
	}
	return pu
}

// SetUploaderID sets the "uploader" edge to the User entity by ID.
func (pu *PhotoUpdate) SetUploaderID(id uuid.UUID) *PhotoUpdate {
	pu.mutation.SetUploaderID(id)
	return pu
}

// SetUploader sets the "uploader" edge to the User entity.
func (pu *PhotoUpdate) SetUploader(u *User) *PhotoUpdate {
	return pu.SetUploaderID(u.ID)
}

// Mutation returns the PhotoMutation object of the builder.
func (pu *PhotoUpdate) Mutation() *PhotoMutation {
	return pu.mutation
}

// ClearUploader clears the "uploader" edge to the User entity.
func (pu *PhotoUpdate) ClearUploader() *PhotoUpdate {
	pu.mutation.ClearUploader()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PhotoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PhotoUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PhotoUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PhotoUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PhotoUpdate) check() error {
	if v, ok := pu.mutation.OriginalName(); ok {
		if err := photo.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "Photo.original_name": %w`, err)}
		}
	}
	if v, ok := pu.mutation.MimeType(); ok {
		if err := photo.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Photo.mime_type": %w`, err)}
		}
	}
	if pu.mutation.UploaderCleared() && len(pu.mutation.UploaderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Photo.uploader"`)
	}
	return nil
}

func (pu *PhotoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(photo.Table, photo.Columns, sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.OriginalName(); ok {
		_spec.SetField(photo.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := pu.mutation.MimeType(); ok {
		_spec.SetField(photo.FieldMimeType, field.TypeString, value)
	}
	if pu.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   photo.UploaderTable,
			Columns: []string{photo.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   photo.UploaderTable,
			Columns: []string{photo.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{photo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PhotoUpdateOne is the builder for updating a single Photo entity.
type PhotoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PhotoMutation
}

// SetOriginalName sets the "original_name" field.
func (puo *PhotoUpdateOne) SetOriginalName(s string) *PhotoUpdateOne {
	puo.mutation.SetOriginalName(s)
	return puo
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (puo *PhotoUpdateOne) SetNillableOriginalName(s *string) *PhotoUpdateOne {
	if s != nil {
		puo.SetOriginalName(*s)
	}
	return puo
}

// SetMimeType sets the "mime_type" field.
func (puo *PhotoUpdateOne) SetMimeType(s string) *PhotoUpdateOne {
	puo.mutation.SetMimeType(s)
	return puo
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (puo *PhotoUpdateOne) SetNillableMimeType(s *string) *PhotoUpdateOne {
	if s != nil {
		puo.SetMimeType(*s)
	}
	return puo
}

// SetUploaderID sets the "uploader" edge to the User entity by ID.
func (puo *PhotoUpdateOne) SetUploaderID(id uuid.UUID) *PhotoUpdateOne {
	puo.mutation.SetUploaderID(id)
	return puo
}

// SetUploader sets the "uploader" edge to the User entity.
func (puo *PhotoUpdateOne) SetUploader(u *User) *PhotoUpdateOne {
	return puo.SetUploaderID(u.ID)
}

// Mutation returns the PhotoMutation object of the builder.
func (puo *PhotoUpdateOne) Mutation() *PhotoMutation {
	return puo.mutation
}

// ClearUploader clears the "uploader" edge to the User entity.
func (puo *PhotoUpdateOne) ClearUploader() *PhotoUpdateOne {
	puo.mutation.ClearUploader()
	return puo
}

// Where appends a list predicates to the PhotoUpdate builder.
func (puo *PhotoUpdateOne) Where(ps ...predicate.Photo) *PhotoUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PhotoUpdateOne) Select(field string, fields ...string) *PhotoUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Photo entity.
func (puo *PhotoUpdateOne) Save(ctx context.Context) (*Photo, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PhotoUpdateOne) SaveX(ctx context.Context) *Photo {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PhotoUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PhotoUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PhotoUpdateOne) check() error {
	if v, ok := puo.mutation.OriginalName(); ok {
		if err := photo.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "Photo.original_name": %w`, err)}
		}
	}
	if v, ok := puo.mutation.MimeType(); ok {
		if err := photo.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Photo.mime_type": %w`, err)}
		}
	}
	if puo.mutation.UploaderCleared() && len(puo.mutation.UploaderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Photo.uploader"`)
	}
	return nil
}

func (puo *PhotoUpdateOne) sqlSave(ctx context.Context) (_node *Photo, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(photo.Table, photo.Columns, sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Photo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, photo.FieldID)
		for _, f := range fields {
			if !photo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != photo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.OriginalName(); ok {
		_spec.SetField(photo.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := puo.mutation.MimeType(); ok {
		_spec.SetField(photo.FieldMimeType, field.TypeString, value)
	}
	if puo.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   photo.UploaderTable,
			Columns: []string{photo.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   photo.UploaderTable,
			Columns: []string{photo.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Photo{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{photo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
