// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/parrotmac/pictorial/ent/photo"
	"github.com/parrotmac/pictorial/ent/user"
)

// PhotoCreate is the builder for creating a Photo entity.
type PhotoCreate struct {
	config
	mutation *PhotoMutation
	hooks    []Hook
}

// SetOriginalName sets the "original_name" field.
func (pc *PhotoCreate) SetOriginalName(s string) *PhotoCreate {
	pc.mutation.SetOriginalName(s)
	return pc
}

// SetMimeType sets the "mime_type" field.
func (pc *PhotoCreate) SetMimeType(s string) *PhotoCreate {
	pc.mutation.SetMimeType(s)
	return pc
}

// SetUploadedAt sets the "uploaded_at" field.
func (pc *PhotoCreate) SetUploadedAt(t time.Time) *PhotoCreate {
	pc.mutation.SetUploadedAt(t)
	return pc
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (pc *PhotoCreate) SetNillableUploadedAt(t *time.Time) *PhotoCreate {
	if t != nil {
		pc.SetUploadedAt(*t)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *PhotoCreate) SetID(u uuid.UUID) *PhotoCreate {
	pc.mutation.SetID(u)
	return pc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pc *PhotoCreate) SetNillableID(u *uuid.UUID) *PhotoCreate {
	if u != nil {
		pc.SetID(*u)
	}
	return pc
}

// SetUploaderID sets the "uploader" edge to the User entity by ID.
func (pc *PhotoCreate) SetUploaderID(id uuid.UUID) *PhotoCreate {
	pc.mutation.SetUploaderID(id)
	return pc
}

// SetUploader sets the "uploader" edge to the User entity.
func (pc *PhotoCreate) SetUploader(u *User) *PhotoCreate {
	return pc.SetUploaderID(u.ID)
}

// Mutation returns the PhotoMutation object of the builder.
func (pc *PhotoCreate) Mutation() *PhotoMutation {
	return pc.mutation
}

// Save creates the Photo in the database.
func (pc *PhotoCreate) Save(ctx context.Context) (*Photo, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PhotoCreate) SaveX(ctx context.Context) *Photo {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PhotoCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PhotoCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PhotoCreate) defaults() {
	if _, ok := pc.mutation.UploadedAt(); !ok {
		v := photo.DefaultUploadedAt()
		pc.mutation.SetUploadedAt(v)
	}
	if _, ok := pc.mutation.ID(); !ok {
		v := photo.DefaultID()
		pc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PhotoCreate) check() error {
	if _, ok := pc.mutation.OriginalName(); !ok {
		return &ValidationError{Name: "original_name", err: errors.New(`ent: missing required field "Photo.original_name"`)}
	}
	if v, ok := pc.mutation.OriginalName(); ok {
		if err := photo.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "Photo.original_name": %w`, err)}
		}
	}
	if _, ok := pc.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "Photo.mime_type"`)}
	}
	if v, ok := pc.mutation.MimeType(); ok {
		if err := photo.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Photo.mime_type": %w`, err)}
		}
	}
	if _, ok := pc.mutation.UploadedAt(); !ok {
		return &ValidationError{Name: "uploaded_at", err: errors.New(`ent: missing required field "Photo.uploaded_at"`)}
	}
	if len(pc.mutation.UploaderIDs()) == 0 {
		return &ValidationError{Name: "uploader", err: errors.New(`ent: missing required edge "Photo.uploader"`)}
	}
	return nil
}

func (pc *PhotoCreate) sqlSave(ctx context.Context) (*Photo, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PhotoCreate) createSpec() (*Photo, *sqlgraph.CreateSpec) {
	var (
		_node = &Photo{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(photo.Table, sqlgraph.NewFieldSpec(photo.FieldID, field.TypeUUID))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pc.mutation.OriginalName(); ok {
		_spec.SetField(photo.FieldOriginalName, field.TypeString, value)
		_node.OriginalName = value
	}
	if value, ok := pc.mutation.MimeType(); ok {
		_spec.SetField(photo.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := pc.mutation.UploadedAt(); ok {
		_spec.SetField(photo.FieldUploadedAt, field.TypeTime, value)
		_node.UploadedAt = value
	}
	if nodes := pc.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   photo.UploaderTable,
			Columns: []string{photo.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_photos = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PhotoCreateBulk is the builder for creating many Photo entities in bulk.
type PhotoCreateBulk struct {
	config
	err      error
	builders []*PhotoCreate
}

// Save creates the Photo entities in the database.
func (pcb *PhotoCreateBulk) Save(ctx context.Context) ([]*Photo, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Photo, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PhotoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PhotoCreateBulk) SaveX(ctx context.Context) []*Photo {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PhotoCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PhotoCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
