// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/parrotmac/pictorial/ent/photo"
	"github.com/parrotmac/pictorial/ent/schema"
	"github.com/parrotmac/pictorial/ent/session"
	"github.com/parrotmac/pictorial/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	photoFields := schema.Photo{}.Fields()
	_ = photoFields
	// photoDescOriginalName is the schema descriptor for original_name field.
	photoDescOriginalName := photoFields[1].Descriptor()
	// photo.OriginalNameValidator is a validator for the "original_name" field. It is called by the builders before save.
	photo.OriginalNameValidator = photoDescOriginalName.Validators[0].(func(string) error)
	// photoDescMimeType is the schema descriptor for mime_type field.
	photoDescMimeType := photoFields[2].Descriptor()
	// photo.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	photo.MimeTypeValidator = photoDescMimeType.Validators[0].(func(string) error)
	// photoDescUploadedAt is the schema descriptor for uploaded_at field.
	photoDescUploadedAt := photoFields[3].Descriptor()
	// photo.DefaultUploadedAt holds the default value on creation for the uploaded_at field.
	photo.DefaultUploadedAt = photoDescUploadedAt.Default.(func() time.Time)
	// photoDescID is the schema descriptor for id field.
	photoDescID := photoFields[0].Descriptor()
	// photo.DefaultID holds the default value on creation for the id field.
	photo.DefaultID = photoDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[1].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[2].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
